### ISSUE TITLE
Wiki code within <code> or indented blocks should be rendered

### ISSUE THREAD

**Issue by pbb72** [nricciar/wikicloth#103]
Mediawiki renders wiki layout code within `<code>` blocks and space-indented blocks. (I've not seen this happen with other code tags, for example `<source>`.)

Wiki code:
```wiki
<code>Code can contain ''italic'' and '''bold''' text, and even [[link]]s</code>
```

Mediawiki output:
```html
<code>Code can contain <i>italic</i> and <b>bold</b> text, and even <a href="/wiki/Link" title="Link">links</a></code>
```

Wikicloth output:
```html
<code>Code can contain ''italic'' and '''bold''' text, and even [[link]]s</code>
```

**Comment by nricciar** [comment]
Duplicate https://github.com/nricciar/wikicloth/issues/76
