### ISSUE TITLE
Unexpected I18n.locale overwrite

### ISSUE THREAD

**Issue by rfc2616** [nricciar/wikicloth#58]
An odd bug in one of our projects came from wikicloth overwriting I18n.locale to the default locale if no locale was explicitly passed in at parser construction time. While it is possible to be sure to pass in the correct locale, it seems like wikicloth shouldn't overwrite this value to system default when no option is passed. Sending a PR that changes the behavior, if you agree.

**Comment by katafrakt** [comment]
It's fixed with https://github.com/nricciar/wikicloth/pull/79
