### ISSUE TITLE
Dependency on rinku breaks JRuby-compatibility

### ISSUE THREAD

**Issue by bartkamphorst** [nricciar/wikicloth#73]
WikiCloth is no longer compatible with JRuby after adding `rinku` as a dependency in [this commit](https://github.com/nricciar/wikicloth/commit/bc4131fa292573653f1161a4943ed473ac9d6da7). Is this something you would consider fixing?

**Comment by dometto** [comment]
May I ask when this fix is going to be released?

**Comment by nricciar** [comment]
hmmm I could probably go ahead and post a new version here in the next day or so. let me make sure there is nothing keeping me from doing so first though.

**Comment by dometto** [comment]
:+1: That would be great

**Comment by dometto** [comment]
Don't mean to bug you too much, but did you find any showstoppers for a new release? I'd like to try and update the wikicloth dependency in github/markup so its specs can be run on jruby.

**Comment by nricciar** [comment]
Sorry that took so long, but I just pushed out v0.8.2

**Comment by bartkamphorst** [comment]
\o/
Thanks!
