### ISSUE TITLE
v0.8.3 release on gem repository

### ISSUE THREAD

**Issue by hiro0107** [nricciar/wikicloth#80]
I am testing WikiCloth from the gem repository, and I've found some bugs which has already been fixed in v0.8.3.
Now on the gem repository, there is only the version 0.8.2 or earlier of wikicloth and I can't find the 0.8.3 version of it.
Do you have a plan to release the 0.8.3 version of wikicloth on the gem repository?

**Comment by bartkamphorst** [comment]
There were some issues pushing the 0.8.3 gem to rubygems. See [here](https://github.com/nricciar/wikicloth/pull/78).

**Comment by ktdreyer** [comment]
Hi David, any more luck pushing 0.8.3 to rubygems? It would be nice to have this version available with all the latest test suite fixes, etc.

**Comment by nricciar** [comment]
pushed it this morning so you should be good to go.

**Comment by bartkamphorst** [comment]
Thanks!
