### ISSUE TITLE
Tables extraction

### ISSUE THREAD

**Issue by djstrong** [nricciar/wikicloth#82]
Is it possible to extract tables from markup? There is WikiCloth::WikiBuffer::Table, but I can't access it by implementing Parser.

**Comment by nricciar** [comment]
Your only real option at the moment would be to override the to_html method in the WikiCloth::WikiBuffer::Table.  this would allow you to access the raw table data prior to it being rendered into html. From there you could pass the table data to whatever you need to though.

**Comment by djstrong** [comment]
Thanks!
