### ISSUE TITLE
Cutting off everything before the double break in a <pre>

### ISSUE THREAD

**Issue by logicplace** [nricciar/wikicloth#83]
Example: `WikiCloth::Parser.new({:data=>"abcdef\n<pre>inpre\n\ndoublebreak\nblah</pre>\n"}).to_html`

Result: `"\n<p>abcdef\n<pre>doublebreak\nblah</pre></p>"`

This only seems to affect pre tags as I tried it with tt and it didn't have this issue. So I would expect something more like tt returns:

Example: `WikiCloth::Parser.new({:data=>"abcdef\n<tt>inpre\n\ndoublebreak\nblah</tt>\n"}).to_html`

Result: `"\n<p>abcdef\n</p><tt>inpre\n\ndoublebreak\nblah</tt>"`

Obviously the paragraph tags are a bit different too, though I care less about that.

**Comment by nricciar** [comment]
Duplicate https://github.com/nricciar/wikicloth/issues/102, closing this one as the other is a bit more descriptive
