### ISSUE TITLE
`has_rdoc` is deprecated with no replacement

### ISSUE THREAD

**Issue by ZPVIP** [nricciar/wikicloth#98]
Notice of bundle:

NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from ....../wikicloth/wikicloth.gemspec:19.

```
  s.has_rdoc = false
```
https://github.com/nricciar/wikicloth/blob/54ad028e541bf5314433712e5cf90d3bd515cf93/wikicloth.gemspec#L19
should be deleted.

**Comment by olleolleolle** [comment]
Fixed in f385bb84db9f96c5b9ddd88b5da8472cb7b214ce

This Issue can be closed now. Thanks for reporting, @ZPVIP!
